"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { InternalLogoutButton } from "@/components/InternalLogoutButton";
import { PropertyWizard } from "@/components/PropertyWizard";

const leadLabels = { new: "Nueva", contacted: "Contactada", qualified: "Calificada", visit: "Visita", closed: "Cerrada", archived: "Archivada" };
const propertyLabels = { draft: "Borrador", published: "Publicada", archived: "Archivada" };
const baseSections = [["dashboard", "Resumen"], ["properties", "Propiedades"], ["catalog", "Catálogo"], ["leads", "Mensajes"]];
const emptyProperty = { id: "", title: "", slug: "", description: "", location: "", zone: "Ciudad de Panamá", operation: "Venta", propertyType: "Apartamento", price: "", priceLabel: "", bedrooms: "0", bathrooms: "0", areaLabel: "", imageUrl: "", featuresText: "", featured: false, status: "draft" };

function initials(value) { return String(value || "?").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function formatDate(value) { return value ? new Intl.DateTimeFormat("es-PA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Sin fecha"; }
function EmptyState({ text }) { return <div className="admin-empty"><strong>Aún no hay registros</strong><p>{text}</p></div>; }
function propertyToForm(property) { return { ...emptyProperty, ...property, propertyType: property.type || property.propertyType || "Apartamento", price: property.price || "", bedrooms: String(property.beds ?? property.bedrooms ?? 0), bathrooms: String(property.baths ?? property.bathrooms ?? 0), areaLabel: property.area || property.areaLabel || "", imageUrl: property.image || property.imageUrl || "", featuresText: (property.amenities || property.features || []).join("\n") }; }

function PropertyEditor({ property, isMaster, onClose, onSaved }) {
  const [form, setForm] = useState(property ? propertyToForm(property) : emptyProperty);
  const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  function update(event) { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); }
  function next() { if (step === 1 && (!form.title || !form.description)) return setError("Completa el título y la descripción antes de continuar."); if (step === 2 && (!form.location || !form.zone || !form.priceLabel)) return setError("Completa ubicación, zona y precio visible antes de continuar."); setError(""); setStep((current) => Math.min(3, current + 1)); }
  async function submit(event) { event.preventDefault(); if (step < 3) return next(); setSaving(true); setError(""); try { const payload = { ...form, features: form.featuresText.split(/\n|,/).map((item) => item.trim()).filter(Boolean), gallery: form.imageUrl ? [form.imageUrl] : [] }; const response = await fetch(property?.id ? `/api/admin/properties/${property.id}` : "/api/admin/properties", { method: property?.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No fue posible guardar la propiedad."); onSaved(data.property); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } }
  return <section className="admin-panel property-editor-panel"><div className="panel-title"><div><span className="eyebrow">Inventario</span><h2>{property ? "Editar propiedad" : "Nueva propiedad"}</h2></div><button className="panel-action" onClick={onClose} type="button">Cerrar</button></div><div className="wizard-progress"><span style={{ width: `${step * 33.333}%` }} /></div><ol className="wizard-steps"><li className={step === 1 ? "active" : ""}>1. Información</li><li className={step === 2 ? "active" : ""}>2. Detalles</li><li className={step === 3 ? "active" : ""}>3. Fotos</li></ol><form className="editor-form property-editor" onSubmit={submit}>
    {step === 1 ? <><div className="form-grid"><label>Título de la propiedad *<input required name="title" value={form.title} onChange={update} placeholder="Apartamento con vista al mar" /></label><label>Enlace corto opcional<input name="slug" value={form.slug} onChange={update} placeholder="Se crea a partir del título" /></label></div><label>Descripción *<textarea required name="description" rows="6" value={form.description} onChange={update} placeholder="Describe los atributos, ventajas y condiciones principales." /></label><div className="form-grid"><label>Operación *<select name="operation" value={form.operation} onChange={update}><option>Venta</option><option>Alquiler</option></select></label><label>Tipo de propiedad *<select name="propertyType" value={form.propertyType} onChange={update}><option>Apartamento</option><option>Casa</option><option>Terreno</option><option>Local comercial</option><option>Oficina</option><option>Finca</option><option>Proyecto</option></select></label></div></> : null}
    {step === 2 ? <><div className="form-grid"><label>Ubicación *<input required name="location" value={form.location} onChange={update} placeholder="Costa del Este, Panamá" /></label><label>Zona *<input required name="zone" value={form.zone} onChange={update} placeholder="Ciudad de Panamá" /></label></div><div className="form-grid thirds"><label>Precio numérico<input name="price" min="0" step="0.01" type="number" value={form.price} onChange={update} /></label><label>Precio visible *<input required name="priceLabel" value={form.priceLabel} onChange={update} placeholder="USD 250,000" /></label><label>Área<input name="areaLabel" value={form.areaLabel} onChange={update} placeholder="125 m²" /></label></div><div className="form-grid"><label>Recámaras<input name="bedrooms" min="0" type="number" value={form.bedrooms} onChange={update} /></label><label>Baños<input name="bathrooms" min="0" step="0.5" type="number" value={form.bathrooms} onChange={update} /></label></div><label>Características<textarea name="featuresText" rows="4" value={form.featuresText} onChange={update} placeholder={"Piscina\nEstacionamientos\nSeguridad 24 horas"} /><small>Una característica por línea.</small></label></> : null}
    {step === 3 ? <><label>Imagen principal<input name="imageUrl" type="url" value={form.imageUrl} onChange={update} placeholder="https://..." /><small>Pega la URL pública de una fotografía. La carga directa se añadirá cuando se conecte almacenamiento.</small></label><div className="form-grid">{isMaster ? <label className="checkbox-row"><input name="featured" type="checkbox" checked={form.featured} onChange={update} /> Mostrar como destacada</label> : <p className="editor-help">Solo la cuenta master puede destacar una propiedad.</p>}<label>Estado<select name="status" value={form.status} onChange={update}><option value="draft">Guardar como borrador</option><option value="published">Publicar ahora</option><option value="archived">Archivar</option></select></label></div></> : null}
    {error ? <p className="form-status error" role="alert">{error}</p> : null}<div className="admin-form-actions">{step > 1 ? <button className="button outline" type="button" onClick={() => { setError(""); setStep((current) => current - 1); }}>Atrás</button> : <button className="button outline" type="button" onClick={onClose}>Cancelar</button>}<button className="button teal" disabled={saving} type="submit">{step < 3 ? "Continuar" : saving ? "Guardando..." : property ? "Guardar cambios" : "Crear propiedad"}</button></div>
  </form></section>;
}

function PropertiesPanel({ properties, isMaster, onRefresh, onPreview }) {
  const [editing, setEditing] = useState(null); const [creating, setCreating] = useState(false);
  if (creating || editing) return <PropertyWizard property={editing} isMaster={isMaster} onClose={() => { setEditing(null); setCreating(false); }} onSaved={async () => { setEditing(null); setCreating(false); await onRefresh(); }} />;
  return <section className="admin-panel"><div className="panel-title"><div><span className="eyebrow">Inventario</span><h2>Propiedades</h2></div><button className="button teal small" onClick={() => setCreating(true)} type="button">Nueva propiedad</button></div>{properties.length ? <><div className="table-scroll"><table className="admin-table"><thead><tr><th>Propiedad</th><th>Asesor</th><th>Operación</th><th>Ubicación</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{properties.map((item) => <tr key={item.id || item.slug}><td><strong>{item.title}</strong><small>{item.type}</small></td><td>{isMaster ? item.advisorName || "Cevenpro" : "Tu cuenta"}</td><td>{item.operation}</td><td>{item.location}</td><td>{item.priceLabel}</td><td><span className={`status property-status ${item.status}`}>{propertyLabels[item.status] || item.status}</span></td><td><div className="table-actions"><button onClick={() => setEditing(item)} type="button">Editar</button>{item.status === "published" ? <button onClick={() => onPreview(item)} type="button">Vista interna</button> : null}</div></td></tr>)}</tbody></table></div><div className="admin-property-list">{properties.map((item) => <article className="admin-property-card" key={item.id || item.slug}><div className="admin-property-card-title"><div><strong>{item.title}</strong><small>{item.type} · {item.operation}</small></div><span className={`status property-status ${item.status}`}>{propertyLabels[item.status] || item.status}</span></div><dl><div><dt>Ubicación</dt><dd>{item.location}</dd></div><div><dt>Precio</dt><dd>{item.priceLabel}</dd></div><div><dt>Asesor</dt><dd>{isMaster ? item.advisorName || "Cevenpro" : "Tu cuenta"}</dd></div></dl><div className="admin-property-card-actions"><button className="button teal small" onClick={() => setEditing(item)} type="button">Editar</button>{item.status === "published" ? <button className="button outline small" onClick={() => onPreview(item)} type="button">Vista interna</button> : null}</div></article>)}</div></> : <EmptyState text="Crea la primera propiedad. Puedes guardarla como borrador o publicarla cuando esté lista." />}<p className="panel-note">Archivar oculta una propiedad de la web sin borrarla ni perder su historial.</p></section>;
}

function CatalogPanel({ properties, selectedSlug, onSelect, onManage }) {
  const published = properties.filter((item) => item.status === "published");
  const selected = published.find((item) => item.slug === selectedSlug);
  if (selected) {
    const gallery = [...new Set([selected.image, ...(selected.gallery || [])].filter(Boolean))];
    return <section className="admin-panel internal-catalog-detail"><div className="panel-title"><div><span className="eyebrow">Vista interna</span><h2>{selected.title}</h2><p>Así aparece esta propiedad dentro del catálogo de CevenPro.</p></div><button className="panel-action" onClick={() => onSelect(null)} type="button">Volver al catálogo</button></div><div className="internal-catalog-detail-grid"><section>{gallery.length ? <div className="internal-catalog-gallery">{gallery.map((image, index) => <img key={image} src={image} alt={`${selected.title}, foto ${index + 1}`} />)}</div> : <div className="internal-catalog-placeholder">Sin fotos</div>}</section><section className="internal-catalog-copy"><span className="status property-status published">Publicada</span><strong className="internal-catalog-price">{selected.priceLabel}</strong><dl><div><dt>Tipo</dt><dd>{selected.type}</dd></div><div><dt>Operación</dt><dd>{selected.operation}</dd></div><div><dt>Ubicación</dt><dd>{selected.location}</dd></div><div><dt>Zona</dt><dd>{selected.zone}</dd></div></dl><p>{selected.description}</p><button className="button teal small" onClick={onManage} type="button">Gestionar propiedades</button></section></div></section>;
  }
  return <section className="admin-panel internal-catalog"><div className="panel-title"><div><span className="eyebrow">Vista interna</span><h2>Catálogo publicado</h2><p>Revisa las publicaciones sin salir de tu panel.</p></div><button className="button outline small" onClick={onManage} type="button">Gestionar propiedades</button></div>{published.length ? <div className="internal-catalog-list">{published.map((item) => <article className="internal-catalog-item" key={item.id || item.slug}>{item.image ? <img src={item.image} alt="" /> : <div className="internal-catalog-placeholder">Sin foto</div>}<div><strong>{item.title}</strong><span>{item.type} · {item.operation}</span><small>{item.location}</small></div><div className="internal-catalog-item-actions"><b>{item.priceLabel}</b><button className="button outline small" onClick={() => onSelect(item.slug)} type="button">Ver detalles</button></div></article>)}</div> : <EmptyState text="Las propiedades publicadas aparecerán aquí para revisarlas sin salir del panel." />}</section>;
}

function LeadsPanel({ leads, onRefresh }) {
  const [selected, setSelected] = useState(null); const [filter, setFilter] = useState("active"); const [status, setStatus] = useState("new"); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const visible = leads.filter((item) => filter === "all" || (filter === "active" ? !["closed", "archived"].includes(item.status) : item.status === filter));
  useEffect(() => { if (selected) { setStatus(selected.status || "new"); setNotes(selected.internal_notes || ""); } }, [selected]);
  async function save(event) { event.preventDefault(); if (!selected) return; setSaving(true); try { const response = await fetch(`/api/admin/leads/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, assignedTo: selected.assigned_to || "", internalNotes: notes }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSelected(null); await onRefresh(); } finally { setSaving(false); } }
  if (selected) return <section className="admin-panel lead-detail-panel"><div className="panel-title"><div><span className="eyebrow">Consulta</span><h2>{selected.name}</h2><p>{selected.property_title || selected.interest}</p></div><button className="panel-action" onClick={() => setSelected(null)} type="button">Cerrar</button></div><div className="lead-information-grid"><section><h3>Contacto</h3><dl><div><dt>Correo</dt><dd>{selected.email}</dd></div><div><dt>WhatsApp</dt><dd>{selected.phone}</dd></div><div><dt>Recibida</dt><dd>{formatDate(selected.created_at)}</dd></div></dl></section><section><h3>Mensaje</h3><p className="lead-message">{selected.notes || "El cliente no agregó observaciones."}</p></section></div><form className="editor-form lead-followup" onSubmit={save}><h3>Seguimiento interno</h3><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}>{Object.entries(leadLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Notas internas<textarea rows="4" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Registra acuerdos o el próximo paso." /></label><button className="button teal small" disabled={saving}>{saving ? "Guardando..." : "Guardar seguimiento"}</button></form></section>;
  return <section className="admin-panel"><div className="panel-title"><div><span className="eyebrow">Consultas de la web</span><h2>Mensajes</h2></div><select className="admin-filter" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="active">Activas</option><option value="all">Todas</option>{Object.entries(leadLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>{visible.length ? <div className="lead-board">{visible.map((item) => <button className="lead-item lead-item-button" key={item.id} onClick={() => setSelected(item)} type="button"><div className="lead-avatar">{initials(item.name)}</div><div><strong>{item.name}</strong><span>{item.property_title || item.interest}</span><small>{item.phone} · {formatDate(item.created_at)}</small></div><div className="lead-actions"><span className={`status lead-status ${item.status}`}>{leadLabels[item.status] || item.status}</span><small>Ver mensaje</small></div></button>)}</div> : <EmptyState text="Los mensajes enviados desde la web aparecerán aquí." />}</section>;
}

function AdvisorsPanel({ advisors, onRefresh }) {
  const [busy, setBusy] = useState(""); const [copied, setCopied] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  async function setStatus(id, status) { setBusy(id); setNotice(""); setError(""); try { const response = await fetch("/api/admin/advisors", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo actualizar la cuenta."); setNotice(status === "active" ? "La cuenta fue aprobada. Ya puede entrar con el correo y la contraseña que registró." : "El estado de la cuenta fue actualizado."); await onRefresh(); } catch (requestError) { setError(requestError.message); } finally { setBusy(""); } }
  async function createResetLink(id) { setBusy(id); setNotice(""); setError(""); try { const response = await fetch("/api/admin/advisors", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: "create-reset-link" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No fue posible crear el enlace."); try { await navigator.clipboard.writeText(data.resetLink); setNotice("Enlace de restablecimiento copiado. Envíalo al WhatsApp confirmado del asesor: vence en 30 minutos y sirve una sola vez."); } catch { window.prompt("Copia este enlace y envíalo al WhatsApp confirmado. Vence en 30 minutos:", data.resetLink); setNotice("Se generó el enlace temporal de restablecimiento."); } } catch (requestError) { setError(requestError.message); } finally { setBusy(""); } }
  async function copyRegistrationLink() { try { await navigator.clipboard.writeText(`${window.location.origin}/registro-asesor`); setCopied(true); window.setTimeout(() => setCopied(false), 2500); } catch { window.prompt("Copia este enlace para el asesor:", `${window.location.origin}/registro-asesor`); } }
  return <section className="admin-panel"><div className="panel-title"><div><span className="eyebrow">Red profesional</span><h2>Asesores</h2><p>Comparte el formulario. Las solicitudes llegan aquí y tú decides a quién darle acceso.</p></div><button className="button outline small" onClick={copyRegistrationLink} type="button">{copied ? "Enlace copiado" : "Copiar enlace de solicitud"}</button></div>{notice ? <p className="form-status">{notice}</p> : null}{error ? <p className="form-status error">{error}</p> : null}{advisors.length ? <div className="advisor-board">{advisors.map((advisor) => { const pending = advisor.status === "disabled" && advisor.application_status === "registered"; const statusLabel = pending ? "Pendiente" : advisor.status === "active" ? "Activa" : advisor.status === "disabled" ? "Desactivada" : "Archivada"; return <article className="advisor-card" key={advisor.id}><div className="lead-avatar">{initials(advisor.name)}</div><div className="advisor-copy"><strong>{advisor.name}</strong><span>{advisor.email} · {advisor.phone || "Sin teléfono"}</span><small>{advisor.applicant_role || "Asesor"}{advisor.nationality ? ` · ${advisor.nationality}` : ""}{advisor.residency_status ? ` · ${advisor.residency_status}` : ""}{advisor.age_range ? ` · ${advisor.age_range}` : ""}</small><small>{advisor.work_mode === "empresa" ? "Trabaja con empresa" : advisor.work_mode === "ambos" ? "Empresa e independiente" : "Independiente"}{advisor.service_zones ? ` · ${advisor.service_zones}` : ""}</small>{advisor.experience ? <small>Experiencia: {advisor.experience}</small> : null}{advisor.recent_activity ? <small className="advisor-activity">Última experiencia: {advisor.recent_activity}</small> : null}<small>{advisor.property_count} propiedades · {advisor.open_lead_count} mensajes abiertos</small></div><div className="advisor-actions"><span className={`status advisor-status ${pending ? "pending" : advisor.status}`}>{statusLabel}</span>{advisor.status === "active" ? <><Link className="advisor-profile-link" href={`/asesores/${advisor.profile_slug}`} target="_blank">Ver perfil</Link><button disabled={busy === advisor.id} onClick={() => createResetLink(advisor.id)} type="button">Restablecer acceso</button><button disabled={busy === advisor.id} onClick={() => setStatus(advisor.id, "disabled")} type="button">Desactivar</button></> : pending ? <><button disabled={busy === advisor.id} onClick={() => setStatus(advisor.id, "active")} type="button">Aprobar acceso</button><button disabled={busy === advisor.id} onClick={() => setStatus(advisor.id, "archived")} type="button">Descartar</button></> : <button disabled={busy === advisor.id} onClick={() => setStatus(advisor.id, "active")} type="button">{advisor.status === "archived" ? "Reactivar" : "Activar"}</button>}</div></article>; })}</div> : <EmptyState text="Las solicitudes para trabajar con Cevenpro aparecerán aquí." />}</section>;
}

function DashboardHome({ properties, leads, advisors, isMaster, setActive, onCatalog }) {
  const published = properties.filter((item) => item.status === "published").length; const newLeads = leads.filter((item) => item.status === "new").length;
  return <><div className="metric-grid admin-metric-grid"><article className="metric-card"><span>Propiedades publicadas</span><strong>{published}</strong><small>{properties.length} registradas en total</small></article><article className="metric-card"><span>Mensajes nuevos</span><strong>{newLeads}</strong><small>Pendientes de primera respuesta</small></article><article className="metric-card"><span>{isMaster ? "Asesores activos" : "Propiedades en total"}</span><strong>{isMaster ? advisors.filter((item) => item.status === "active").length : properties.length}</strong><small>{isMaster ? `${advisors.length} registrados` : "Gestionadas por ti"}</small></article></div><div className="admin-grid admin-summary-grid"><section className="admin-panel"><div className="panel-title"><div><span className="eyebrow">Más recientes</span><h2>Últimos mensajes</h2></div><button className="panel-action" onClick={() => setActive("leads")} type="button">Ver todos</button></div>{leads.slice(0, 5).length ? <div className="lead-board compact">{leads.slice(0, 5).map((item) => <article className="lead-item" key={item.id}><div className="lead-avatar">{initials(item.name)}</div><div><strong>{item.name}</strong><span>{item.property_title || item.interest}</span><small>{formatDate(item.created_at)}</small></div><span className={`status lead-status ${item.status}`}>{leadLabels[item.status] || item.status}</span></article>)}</div> : <EmptyState text="Las consultas enviadas desde la web aparecerán aquí." />}</section><section className="admin-panel admin-quick-actions"><span className="eyebrow">Acciones</span><h2>¿Qué deseas hacer?</h2><button className="button teal" onClick={() => setActive("properties")} type="button">Agregar una propiedad</button>{isMaster ? <button className="button outline" onClick={() => setActive("advisors")} type="button">Gestionar asesores</button> : null}<button className="button outline" onClick={onCatalog} type="button">Ver catálogo</button></section></div></>;
}

export function AdminDashboard({ initialUser }) {
  const isMaster = initialUser.role === "master"; const sections = isMaster ? [...baseSections, ["advisors", "Asesores"]] : baseSections;
  const [active, setActive] = useState("dashboard"); const [catalogSelection, setCatalogSelection] = useState(null); const [properties, setProperties] = useState([]); const [leads, setLeads] = useState([]); const [advisors, setAdvisors] = useState([]); const [notifications, setNotifications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const loadData = useCallback(async () => { setLoading(true); setError(""); try { const calls = [fetch("/api/admin/properties", { cache: "no-store" }), fetch("/api/admin/leads", { cache: "no-store" }), fetch("/api/admin/notifications", { cache: "no-store" })]; if (isMaster) calls.push(fetch("/api/admin/advisors", { cache: "no-store" })); const responses = await Promise.all(calls); const data = await Promise.all(responses.map((response) => response.json())); if (!responses[0].ok || !responses[1].ok) throw new Error(data.find((item) => item.error)?.error || "No fue posible cargar el panel."); setProperties(data[0].properties || []); setLeads(data[1].leads || []); setNotifications(data[2].notifications || []); if (isMaster && responses[3]?.ok) setAdvisors(data[3].advisors || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, [isMaster]);
  useEffect(() => { loadData(); const section = new URLSearchParams(window.location.search).get("seccion"); if (section && sections.some(([key]) => key === section)) setActive(section); }, [loadData]);
  const unread = notifications.filter((item) => !item.read_at).length;
  function openCatalog(property) { setCatalogSelection(property?.slug || null); setActive("catalog"); }
  async function openNotifications() { setActive("dashboard"); await Promise.all(notifications.filter((item) => !item.read_at).map((item) => fetch("/api/admin/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id }) }))); setNotifications((items) => items.map((item) => ({ ...item, read_at: item.read_at || new Date().toISOString() }))); }
  const content = active === "dashboard" ? <DashboardHome properties={properties} leads={leads} advisors={advisors} isMaster={isMaster} setActive={setActive} onCatalog={() => openCatalog()} /> : active === "properties" ? <PropertiesPanel properties={properties} isMaster={isMaster} onRefresh={loadData} onPreview={openCatalog} /> : active === "catalog" ? <CatalogPanel properties={properties} selectedSlug={catalogSelection} onSelect={setCatalogSelection} onManage={() => setActive("properties")} /> : active === "leads" ? <LeadsPanel leads={leads} onRefresh={loadData} /> : <AdvisorsPanel advisors={advisors} onRefresh={loadData} />;
  return <div className="admin-page"><header className="admin-header"><div className="shell"><button className="admin-brand-button" onClick={() => setActive("dashboard")} type="button"><img src="/brand/cevenpro-logo.svg" alt="Cevenpro" /></button><div className="admin-header-actions"><button className="notification-button" onClick={openNotifications} type="button">Notificaciones{unread ? <b>{unread}</b> : null}</button><span className="role-chip">{isMaster ? "Master" : "Asesor"}</span><button className="button outline small catalog-button" onClick={() => openCatalog()} type="button">Catálogo</button><InternalLogoutButton redirectTo={isMaster ? "/admin" : "/equipo"} /></div></div></header><div className="admin-shell"><aside className="admin-sidebar"><strong>{initialUser.name || "Cevenpro"}</strong>{sections.map(([key, label]) => <button className={active === key ? "active" : ""} key={key} onClick={() => { setCatalogSelection(null); setActive(key); }} type="button">{label}</button>)}</aside><main className="admin-main">{initialUser.legacy && isMaster ? <div className="admin-alert setup-alert"><strong>Activa tu cuenta master personal</strong><p>Tu acceso actual sigue funcionando, pero necesitas una cuenta con correo para recuperar la contraseña y administrar con trazabilidad.</p><Link className="button teal small" href="/activar-master">Activar cuenta master</Link></div> : null}<div className="admin-title"><div><span className="eyebrow">Gestión comercial</span><h1>{sections.find(([key]) => key === active)?.[1]}</h1><p>{active === "catalog" ? "Revisa las publicaciones sin abandonar el panel." : isMaster ? "Controla propiedades, asesores y las consultas que llegan desde la web." : "Gestiona tus propiedades y responde las consultas asignadas."}</p></div><button className="panel-action" disabled={loading} onClick={loadData} type="button">{loading ? "Cargando..." : "Actualizar"}</button></div>{notifications.slice(0, 3).filter((item) => !item.read_at).map((item) => <button className="notification-strip" key={item.id} onClick={openNotifications} type="button"><strong>{item.title}</strong><span>{item.body}</span></button>)}{error ? <div className="admin-alert" role="alert"><strong>No pudimos cargar el panel.</strong><p>{error}</p><button className="button outline small" onClick={loadData} type="button">Intentar nuevamente</button></div> : loading ? <div className="admin-loading">Cargando información...</div> : content}</main></div></div>;
}
