export const locationSuggestions = [
  { label: "Parque Lefevre, Panama", province: "Panama", district: "Parque Lefevre" },
  { label: "Coronado, Panama Oeste", province: "Panama Oeste", district: "Coronado" },
  { label: "San Francisco, Panama", province: "Panama", district: "San Francisco" },
  { label: "El Cangrejo, Panama", province: "Panama", district: "El Cangrejo" },
  { label: "Obarrio, Panama", province: "Panama", district: "Obarrio" },
  { label: "Costa del Este, Panama", province: "Panama", district: "Costa del Este" },
  { label: "Bella Vista, Panama", province: "Panama", district: "Bella Vista" },
  { label: "Via Espana, Panama", province: "Panama", district: "Via Espana" },
  { label: "Tumba Muerto, Panama", province: "Panama", district: "Tumba Muerto" },
  { label: "Brisas del Golf, Panama", province: "Panama", district: "Brisas del Golf" },
  { label: "Juan Diaz, Panama", province: "Panama", district: "Juan Diaz" },
  { label: "Tocumen, Panama", province: "Panama", district: "Tocumen" },
  { label: "Arraijan, Panama Oeste", province: "Panama Oeste", district: "Arraijan" },
  { label: "La Chorrera, Panama Oeste", province: "Panama Oeste", district: "La Chorrera" },
  { label: "Boquete, Chiriqui", province: "Chiriqui", district: "Boquete" },
  { label: "David, Chiriqui", province: "Chiriqui", district: "David" },
  { label: "Santiago, Veraguas", province: "Veraguas", district: "Santiago" },
  { label: "Penonome, Cocle", province: "Cocle", district: "Penonome" },
  { label: "Chitre, Herrera", province: "Herrera", district: "Chitre" },
  { label: "Las Tablas, Los Santos", province: "Los Santos", district: "Las Tablas" }
];
