export const locationSuggestions = [
  { label: "Parque Lefevre, Panama", province: "Panama", district: "Parque Lefevre" },
  { label: "Rio Abajo, Panama", province: "Panama", district: "Rio Abajo" },
  { label: "Pueblo Nuevo, Panama", province: "Panama", district: "Pueblo Nuevo" },
  { label: "Betania, Panama", province: "Panama", district: "Betania" },
  { label: "El Dorado, Panama", province: "Panama", district: "El Dorado" },
  { label: "Condado del Rey, Panama", province: "Panama", district: "Condado del Rey" },
  { label: "12 de Octubre, Panama", province: "Panama", district: "12 de Octubre" },
  { label: "Hato Pintado, Panama", province: "Panama", district: "Hato Pintado" },
  { label: "Via Argentina, Panama", province: "Panama", district: "Via Argentina" },
  { label: "Coronado, Panama Oeste", province: "Panama Oeste", district: "Coronado" },
  { label: "San Francisco, Panama", province: "Panama", district: "San Francisco" },
  { label: "El Cangrejo, Panama", province: "Panama", district: "El Cangrejo" },
  { label: "Obarrio, Panama", province: "Panama", district: "Obarrio" },
  { label: "Costa del Este, Panama", province: "Panama", district: "Costa del Este" },
  { label: "Punta Pacifica, Panama", province: "Panama", district: "Punta Pacifica" },
  { label: "Paitilla, Panama", province: "Panama", district: "Paitilla" },
  { label: "Marbella, Panama", province: "Panama", district: "Marbella" },
  { label: "Bella Vista, Panama", province: "Panama", district: "Bella Vista" },
  { label: "Via Espana, Panama", province: "Panama", district: "Via Espana" },
  { label: "Tumba Muerto, Panama", province: "Panama", district: "Tumba Muerto" },
  { label: "Brisas del Golf, Panama", province: "Panama", district: "Brisas del Golf" },
  { label: "Juan Diaz, Panama", province: "Panama", district: "Juan Diaz" },
  { label: "Los Pueblos, Panama", province: "Panama", district: "Los Pueblos" },
  { label: "Don Bosco, Panama", province: "Panama", district: "Don Bosco" },
  { label: "Pedregal, Panama", province: "Panama", district: "Pedregal" },
  { label: "Las Cumbres, Panama", province: "Panama", district: "Las Cumbres" },
  { label: "Las Mananitas, Panama", province: "Panama", district: "Las Mananitas" },
  { label: "24 de Diciembre, Panama", province: "Panama", district: "24 de Diciembre" },
  { label: "Tocumen, Panama", province: "Panama", district: "Tocumen" },
  { label: "Panama Pacifico, Panama Oeste", province: "Panama Oeste", district: "Panama Pacifico" },
  { label: "Veracruz, Panama Oeste", province: "Panama Oeste", district: "Veracruz" },
  { label: "Arraijan, Panama Oeste", province: "Panama Oeste", district: "Arraijan" },
  { label: "La Chorrera, Panama Oeste", province: "Panama Oeste", district: "La Chorrera" },
  { label: "Nuevo Arraijan, Panama Oeste", province: "Panama Oeste", district: "Nuevo Arraijan" },
  { label: "Vista Alegre, Panama Oeste", province: "Panama Oeste", district: "Vista Alegre" },
  { label: "Chorrera Centro, Panama Oeste", province: "Panama Oeste", district: "Chorrera Centro" },
  { label: "San Carlos, Panama Oeste", province: "Panama Oeste", district: "San Carlos" },
  { label: "Boquete, Chiriqui", province: "Chiriqui", district: "Boquete" },
  { label: "David, Chiriqui", province: "Chiriqui", district: "David" },
  { label: "Santiago, Veraguas", province: "Veraguas", district: "Santiago" },
  { label: "Penonome, Cocle", province: "Cocle", district: "Penonome" },
  { label: "Chitre, Herrera", province: "Herrera", district: "Chitre" },
  { label: "Las Tablas, Los Santos", province: "Los Santos", district: "Las Tablas" }
];
